### ISSUE TITLE
[IDEA] Expand on rainbowfish variety greatly

### ISSUE THREAD

**Issue by Sunconure11** [SomeMelonShark/Fish_and_Bizz#2]
Many, many differing species exist in both captivity and the wild, not just the boesemanis. However... listing them off would be... nightmarish.

Also, maybe add an Easter egg variant that is a reference to The Rainbow Fish, a children's book by Marcus Pfister?

**Comment by SomeMelonShark** [comment]
I could totally add that, I have been thinking of adding rare variants similar to Shiny Pokemon.

**Comment by SomeMelonShark** [comment]
Rainbowfish have variants now
